### ISSUE TITLE
Multi-factor authentication 

### ISSUE THREAD

**Issue by JonathanNiesel** [Azure/azure-data-lake-store-python#111]
Hi, 
I try to connect with the following line:
`token = lib.auth(tenant_id, username, pasr)`,
but it returns the following error:
`AdalError: Get Token request returned http error: 400 and server response: {"error":"interaction_required","error_description":"AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access '797f4846-ba00-4fd7-ba43-XXXXXXX'.\r\nTrace ID: 438223a7-da6d-473d-bdf5-XXXXXXX\r\nCorrelation ID: 03d712aa-d504-4afb-be04-XXXXXXX\r\nTimestamp: 2016-11-08 13:51:43Z","error_codes":[50076],"timestamp":"2016-11-08 13:51:43Z","trace_id":"438223a7-da6d-473d-bdf5-XXXXXX","correlation_id":"03d712aa-d504-4afb-be04-XXXXXXX"}`

Is there a possibility to access while using two-factor authentication? 
`

**Comment by begoldsm** [comment]
This is possible but much more involved and it will require a slight code change to modify the token for refreshability. I will work on getting this included in the auth library.
