### ISSUE TITLE
Task 3.3: Addition of performance tests for several use cases

### ISSUE THREAD

**Issue by rrenfrow86** [Azure/azure-data-lake-store-python#12]
Addition of performance tests to measure performance for large files, folders full of small and mixed file sizes. Once stable, we will integrate these tests into our existing performance testing and reporting service.

**Comment by begoldsm** [comment]
@martindurant @jbcrail have some performance tests like these been run on your side? I would like to see if we can get some of the below cases integrated in some way (probably not in our recording framework, though):
Upload/Download 100GB file
Upload/Download 10,000 1MB files in a nested directory structure (total of 10GB)

**Comment by martindurant** [comment]
No chance on my connection - how about your's, Joseph?
Perhaps we need an ec2 test machine for this (network banbwidth is typically 100MB/s to, for example, s3)

**Comment by jbcrail** [comment]
My connection is adequate, but double-digit GBs would be too slow for me. I'm fine with any solution that is repeatable and relatively easy to setup for benchmarks.

**Comment by mcg1969** [comment]
I've got a gigabit connection at home... No guarantee that there wouldn't be a bottleneck in between, but perhaps I could test some things.

**Comment by begoldsm** [comment]
@mcg1969 @jbcrail @martindurant I can also give you all access to the D14 machine we have been using for perf testing on our side, which gives a 10gigabit nic, SSD and 112GB of memory, which will make the process of building and testing the benchmark script/tool much easier. I think the important thing is that we give an examplar tool that anyone can run on their "good" machine to showcase the performance of our tools.

**Comment by rrenfrow86** [comment]
@begoldsm - I believe we can call this 'done' for our purposes - I'm sure there will be additional performance tests your perf team will want to see but without those now there won't be time to add any more. They could become new issues to track. Also the benchmarking script has been developed and in use by both sides.

**Comment by begoldsm** [comment]
I agree. The benchmark script satisfies this issue for adhoc testing. We do need separate tests that validate  the core functionality of the uploader/downloader (unit tests) that run during CI, though, as we are relying on those tests to quickly detect any breaking changes in the core logic. I will open a new issue for that.

**Comment by martindurant** [comment]
We do have unit-tests for the up/downloader, which run on CI using VCR, in files tests/test_multithread.py, tests/test_transfer.py

**Comment by begoldsm** [comment]
Yup, and there is an open issue already tracking additional validation tests that @jbcrail opened (https://github.com/Azure/azure-data-lake-store-python/issues/78)
