### ISSUE TITLE
Task 4.1: Stabilize work of milestones 1-3 and confirm code coverage

### ISSUE THREAD

**Issue by rrenfrow86** [Azure/azure-data-lake-store-python#13]

**Comment by begoldsm** [comment]
@jbcrail @rrenfrow86 do we have a status update on validation of code coverage, or is there something I need to do in order to get something like coveralls running against this repo?

**Comment by begoldsm** [comment]
I am closing this as we now have consistent code coverage reports and a known set of additional tests to create tracked by #78
