### ISSUE TITLE
[Feature request]: Delimiter Support for file and folder upload

### ISSUE THREAD

**Issue by begoldsm** [Azure/azure-data-lake-store-python#132]
This is a nice to have enhancement that allows for record boundaries to be honored during upload, so that no data is uploaded in the middle of a record.

Work required for this:
1. Add functionality to properly chunk large files on delimiter terminations, so that no records span chunks
2. Add awareness of all chunks to the delimiter searching logic to allow for robust error handling and validation.
3. Add E2E tests.

Cost:
~40 hours.

**Comment by akharit** [comment]
Closing as part of triage of old issues. Will reopen in case of customer demand.
