### ISSUE TITLE
Task 4.2: Integrate custom functionality with the existing Azure SDK for Python

### ISSUE THREAD

**Issue by rrenfrow86** [Azure/azure-data-lake-store-python#14]
This includes proper packaging and naming, ensure inclusion of any common dependencies for things like error handling (ideally this is done in an ongoing basis during development in milestone one, but just in case anything is missed it is fixed here).

**Comment by matt1883** [comment]
Recommended package name:  azure-datalake-store

**Comment by begoldsm** [comment]
I am closing this since we have a separate task for the package explicitly: #15
