### ISSUE TITLE
Task 4.3: Package publishing

### ISSUE THREAD

**Issue by rrenfrow86** [Azure/azure-data-lake-store-python#15]
Get the functionality ready for package publishing, which includes ensuring our getting started documentation, samples and readthedocs code documentation is ready and has been reviewed.

**Comment by begoldsm** [comment]
@rrenfrow86 I don't think we have gotten to the point where packages are ready to be published yet (since naming isn't quite right). I am re-activating this task as in-progress for now.
Package name should be: `azure-datalake-store`

**Comment by begoldsm** [comment]
@jbcrail can you confirm the package naming and point me to a PR that has it if this has already been done?

**Comment by jbcrail** [comment]
@begoldsm We still use `adlfs` as the name of the package and module. It's easy to rename the package to `azure-datalake-store`, but what is the module naming convention? Possible examples when importing:

- `import adlfs`
- `import adls`
- `import azure_datalake_store`
- `import azure.datalake.store` (other Azure projects seem to follow this)

**Comment by begoldsm** [comment]
@jbcrail we should use the import pattern that the other azure projects use, which would be the last one in your list as you mentioned.

**Comment by begoldsm** [comment]
The package naming is ready!
