### ISSUE TITLE
Download Folder Api

### ISSUE THREAD

**Issue by drcrook1** [Azure/azure-data-lake-store-python#151]
This is an enhancement request that would be great to have.

Here is what I tried to build:
`def DownloadFolder(remote, local, threads = 64, overwrite = False, filemanager = None):
    if(filemanager == None):
        filemanager = GetADLFileManager()
    ADLDownloader(filemanager, lpath=local, rpath=remote, nthreads=threads, overwrite=overwrite, buffersize=4194304, blocksize=4194304)
    `

I would like to use it via:

`DownloadFolder('/doc_suite/', '/usr/local/db/doc_suite/')`

**Comment by drcrook1** [comment]
Just adding more here; it appears to not be downloading the folder via this method.  I am ssh'd into the server and doing ls -a to list files as they should hopefully be coming in and they appear to not be showing.  The full directory download is ~100 gb.

**Comment by drcrook1** [comment]
Any info on this?  The docs say my use case should work; but it obviously isn't.  I currently have several engineers assigned to solve for a work around.  This is business critical impact.

**Comment by begoldsm** [comment]
@drcrook1 can you enable logging for your run to see what is going on and paste the error logs here? What version of azure-datalake-store are you using? If it is < 0.0.5 please upgrade to the latest version.

**Comment by drcrook1** [comment]
How do I enable logging?  I do have the latest version of azure-datalake-store as of today.

**Comment by begoldsm** [comment]
@drcrook1 this has been resolved in the latest version of the SDK (0.0.6). Please update your SDK and give it a shot!
