### ISSUE TITLE
Feature Request: Create nested folder structure during upload if not already present.

### ISSUE THREAD

**Issue by drcrook1** [Azure/azure-data-lake-store-python#153]
Here is the output of the command:

RemoteException":{"exception":"FileNotFoundException","message":"Folder does not exist: /mnt/doc_suite/rvl_cdip_raw/labels [c0c0aeec-2c4d-4545-8f34-fc82bc26688d][2017-04-01T20:39:35.0374181-07:00]","javaClassName":"java.io.FileNotFoundException"}}'

I currently have several engineers working simultaneously and may generate all sorts of folder structures.  These structures should be able to be managed by a simple upload/download.  Attempting to upload into a folder structure should create that structure if it doesn't exist.

Work around available, however as our structures get more complex this will become increasingly painful.

Thanks!

**Comment by begoldsm** [comment]
Thanks for the report @drcrook1! I will tag this as an enhancement that will be triaged and planned for our next milestone.

**Comment by begoldsm** [comment]
@drcrook1 this should now be fixed in the latest version of the SDK (0.0.10). Please give it a shot and let me know if you are still experiencing problems
