### ISSUE TITLE
Task 5.1: Convenience layer for auto-generated clients

### ISSUE THREAD

**Issue by rrenfrow86** [Azure/azure-data-lake-store-python#16]
This is much lower priority than the previous four milestones, but if we have time it would be good to go over the auto-generated client functionality for our other four clients and see if there are any good quality of life improvements we can make for users.

**Comment by begoldsm** [comment]
I am closing this milestone as not needed. Auto-Generated clients will use the CLI as their convenience layer which will be tracked separately.
