### ISSUE TITLE
Automatically refresh service principal access token

### ISSUE THREAD

**Issue by matt1883** [Azure/azure-data-lake-store-python#165]
The built-in authentication logic accepts service principal credentials to fetch an access token once. When this access token expires, the authentication logic does not refresh the access token.

The access token should be refreshed on-demand, if the existing token has expired.

This allows the user of the SDK to not worry about manually refreshing the token in the case of service principal auth, much like the existing support for refreshing user tokens.

Note: Special consideration may be needed re: how the service principal's credentials are stored for re-use when fetching a new token. Other Azure SDKs for Python (e.g., Azure SDK's auth library) may provide insight here.

**Comment by begoldsm** [comment]
This is resolved and published by PR #167
