### ISSUE TITLE
AccessControlException when accessing the file uploaded by Python script from portal

### ISSUE THREAD

**Issue by jerrysoft-x** [Azure/azure-data-lake-store-python#168]
I uploaded a test file to Azure Data Lake Store through Python script with login as an Web App account, however I'm the owner of this ADL and I confirmed I have all the access to this uploaded file in the file properties, when I try to see the content of the uploaded file in File Preview in Azure Portal, I got #AccessControlException telling me I'm not authorized. I don't understand that, to me this is a obvious bug, isn't it?

I have the same problem in portal when opening a folder created by python script, got the same AccessControlException.
![20170703141311](https://user-images.githubusercontent.com/25337098/27781906-c8e55fba-6002-11e7-95e3-7a58b2630900.png)
![20170703141328](https://user-images.githubusercontent.com/25337098/27781907-c8e60a96-6002-11e7-9c34-ccd4b043bfcf.png)

**Comment by jerrysoft-x** [comment]
The error has gone after a day, not sure what happened, Azure need 24h to sync access settings?

**Comment by begoldsm** [comment]
@jerrysoft-x If your user account is the ADLS account owner but does not have explicit ACL permissions on any files/folders, then yes, it does take some time for the access to propagate on newly created items by other users/applications. To avoid this, I would recommend configuring access on the root directly for an "owners" security group as a default ACL, which will rapidly propagate to all sub-items created **after** the default ACL is created (existing items will not be affected).
