### ISSUE TITLE
Could not find cli.py in the library

### ISSUE THREAD

**Issue by jerrysoft-x** [Azure/azure-data-lake-store-python#170]
I'm reading the document of azure data lake store in http://azure-datalake-store.readthedocs.io/en/latest/, in the chapter "Command Line Usage", the code sample is running "python cli.py ls -l".

However, I haven't found cli.py in azure.datalake.store library, so I wonder if it is not available anymore?

**Comment by begoldsm** [comment]
@jerrysoft-x It is present in the Samples folder: https://github.com/Azure/azure-data-lake-store-python/blob/master/samples/cli.py

For information on using it:
https://github.com/Azure/azure-data-lake-store-python#command-line-sample-usage
