### ISSUE TITLE
Race condition due to `transfer` future `done_callback` that depends on state that may set after it's execution

### ISSUE THREAD

**Issue by clehene** [Azure/azure-data-lake-store-python#177]
### Description
I noticed this while trying to figure out why `client.run()` hangs in tests if the transfer function doesn't sleep a bit.

#### Background
Upon calling `submit` on a `ThreadPoolExecutor` a future is returned, but the task can be immediately executed (i.e. there's no `start()` on the pool).
A done callback can be a added on the future, but it depends on actually submitting the future.
`add_done_callback` has internal logic that will execute the callback immediately if the future has already finished (https://github.com/python/cpython/blob/master/Lib/concurrent/futures/_base.py#L376)

#### Actual problem
The problem is that the callback for transfer (`_update`) is dependent on state that is added only after it executes.
Mainly it checks for the future reference in `cfutures`

    if future in self._cfutures:
    ...

However the future is added to `cfutures` after submit and callback

```
    def _start(self, src, dst):
            ...
            future = self._submit(
                self._transfer, self._adlfs, src, name, offset,
                self._chunks[obj]['expected'], self._buffersize,
                self._blocksize)
            # THE CODE ABOVE DEPENDS ON THE FOLLOWING STATEMENT
            self._cfutures[future] = obj

...
    def _submit(self, fn, *args, **kwargs):
        kwargs['shutdown_event'] = self._shutdown_event
        future = self._pool.submit(fn, *args, **kwargs)        
        future.add_done_callback(self._update)
        return future
```

Later, `monitor` will wait until `self.active` returns `False`, which never happens since the condition `not self._fstates.contains_none('pending', 'transferring', 'merging')` is dependent on the branch that never gets executed in `_update`

---

### Reproduction Steps
Remove the `sleep` in one of the tests that calls `client.run()` (e.g. https://github.com/Azure/azure-data-lake-store-python/blob/master/tests/test_transfer.py#L36) and see how the test hangs.

### Environment summary

**SDK Version:** What version of the SDK  are you using? (pip show azure-datalake-store)
`0.0.14`

**Comment by begoldsm** [comment]
#178 resolves this issue. Thank you for the contribution @clehene!
