### ISSUE TITLE
azure/datalake/store/transfer.py missing _submit in master

### ISSUE THREAD

**Issue by spula** [Azure/azure-data-lake-store-python#190]
### Description
**Outline the issue here:**
  File "C:\Python\lib\concurrent\futures\_base.py", line 297, in _invoke_callbac
ks
    callback(self)
  File "C:\Python\lib\site-packages\azure\datalake\store\transfer.py", line 434,
 in _update
    merge_future = self._submit(
AttributeError: 'ADLTransferClient' object has no attribute '_submit'
end upload

---

### Reproduction Steps
multithread.ADLUploader(adlsFileSystemClient, lpath=inputpath, rpath=destpath, nthreads=64, overwrite=True)
** Enumerate the steps to reproduce the issue here:**

### Environment summary

**SDK Version:** What version of the SDK  are you using? (pip show azure-datalake-store)
Answer here:
$ pip show azure-datalake-store
Name: azure-datalake-store
Version: 0.0.15
Summary: Azure Data Lake Store Filesystem Client Library for Python
Home-page: https://github.com/Azure/azure-data-lake-store-python
Author: Microsoft Corporation
Author-email: ptvshelp@microsoft.com
License: MIT License
Location: c:\python\lib\site-packages
Requires: adal, cffi, msrest

**Python Version:** What Python version are you using? Is it 64-bit or 32-bit?  
Answer here: 64

**OS Version:** What OS and version are you using?  
Answer here:windows server 2012R2

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here:Windows

**Comment by chdevala** [comment]
This issue is fixed in 0.0.16 release.
