### ISSUE TITLE
Formatting is broken on PyPi landing page

### ISSUE THREAD

**Issue by begoldsm** [Azure/azure-data-lake-store-python#194]
### Description
**Outline the issue here:**
The formatting of the README.rst and HISTORY.rst is broken, resulting in a plain text landing page on PyPi (see here: https://pypi.python.org/pypi/azure-datalake-store/0.0.16). You can see the difference by looking at this previous version of the package: https://pypi.python.org/pypi/azure-datalake-store/0.0.14

Both version 0.0.16 and 0.0.15 have this broken formatting.

---

### Reproduction Steps
** Enumerate the steps to reproduce the issue here:**

### Environment summary

**SDK Version:** What version of the SDK  are you using? (pip show azure-datalake-store)
Answer here:

**Python Version:** What Python version are you using? Is it 64-bit or 32-bit?  
Answer here:

**OS Version:** What OS and version are you using?  
Answer here:

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here:

**Comment by milanchandna** [comment]
This was fixed in 0.0.17 version.
For reference:
https://pypi.python.org/pypi/azure-datalake-store/0.0.17
https://pypi.python.org/pypi/azure-datalake-store/0.0.18
