### ISSUE TITLE
Frequent Connection Reset errors with 0.0.17

### ISSUE THREAD

**Issue by argoneus** [Azure/azure-data-lake-store-python#200]
### Description
**Outline the issue here:**
We recently upgraded to version 0.0.17 and have been experiencing a multitude of "Connection Reset" errors when interacting with ADLS.

Example error:

`DatalakeRESTException: HTTP error: ConnectionError(ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')),)`

---

### Reproduction Steps
** Enumerate the steps to reproduce the issue here:**
1. Authenticate to ADLS
2. Get a list of files from a directory listing
3. Iterate over file list
4.  Open each file into a pandas dataframe, e.g.
    `df = pd.read_csv(adl.open(file_))`

The errors are frequent but occur on separate files, i.e. it's not reproducible on an individual file basis.  We're seeing the error 60-70% of the time when reading files in a directory listing.

As a mitigation step, I downgraded azure-datalake-store to 0.0.16, and the issue improved dramatically.  Now seeing the Connection Reset error perhaps <5% of the time.

### Environment summary

**SDK Version:** What version of the SDK  are you using? (pip show azure-datalake-store)
Answer here:
0.0.17

**Python Version:** What Python version are you using? Is it 64-bit or 32-bit?  
Answer here:
Python 3.6.1 :: Anaconda 4.4.0 (64-bit)

**OS Version:** What OS and version are you using?  
Answer here:
Ubuntu Linux 16.04

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here:
Jupyter notebook/bash on Ubuntu Linux

**Comment by milanchandna** [comment]
Are you still facing these errors in version > 0.0.16?
Also please share the account name and recent timestamp when the errors were occuring.

**Comment by argoneus** [comment]
Yes, I'm still seeing these issues in 0.0.18.  Which account name do you need?

**Comment by milanchandna** [comment]
Actually there is not much diff in 0.0.16 and 0.0.17
If you are really sure that there is significant difference in behavior in these 2 versions for the scenario you mentioned then we have to check the authentication resource that is being used.
Can you give me some more info please.
1. account name: adl account or store_name
2. Are you passing resource while fetching token. It is usually passed in this method: lib.auth(tenant_id, username, password)
3. Can I please get some debug logs when you are facing Connection reset problems or Halt problem.
4. What is the average file size which you are trying to open? And how big is the list which you are iterating and opening?

**Comment by argoneus** [comment]
We're no longer seeing this issue, so we can close this one.
