### ISSUE TITLE
pkg_resources.DistributionNotFound: The 'futures; python_version <= "2.7"' distribution was not found

### ISSUE THREAD

**Issue by vsandeepsrivastav** [Azure/azure-data-lake-store-python#206]
### Description
Including azure==2.0.0 as a dependency (in setup.py file install_requires section) fails for any library consuming azure due to the following error:

`pkg_resources.DistributionNotFound: The 'futures; python_version <= "2.7"' distribution was not found and is required by azure-datalake-store
`
This is a blocker as I am sure the world has moved from consuming any version of python less than 2.7.
https://github.com/Azure/azure-data-lake-store-python/blob/master/setup.py#L55
Can this be removed?
---

### Reproduction Steps
** Enumerate the steps to reproduce the issue here:**

### Environment summary

**SDK Version:** What version of the SDK  are you using? (pip show azure-datalake-store)
Answer here:
```
Name: azure-datalake-store
Version: 0.0.18
Summary: Azure Data Lake Store Filesystem Client Library for Python
Home-page: https://github.com/Azure/azure-data-lake-store-python
Author: Microsoft Corporation
Author-email: ptvshelp@microsoft.com
License: MIT License
Location: /Library/Python/2.7/site-packages
Requires: futures, msrest, adal, cffi, pathlib2
```

**Python Version:** What Python version are you using? Is it 64-bit or 32-bit?  
Answer here:
```
$ python --version
Python 2.7.10
```
**OS Version:** What OS and version are you using?  
Answer here:
```
$ uname -ar
Darwin lab-mac-8a2dbf 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64
```
**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: bash

**Comment by lmazuel** [comment]
I would not suggest to remove that, this probably just mean that you need to update your pip version.

**Comment by milanchandna** [comment]
I think this is not a problem with 2.x.x but with 2.7.x
Can you please try it with 2.7.0 and 3.x.x rather than 2.7.10 and see if it works.
