### ISSUE TITLE
Unable to apply acl loaded from other file

### ISSUE THREAD

**Issue by dgfmdrv** [Azure/azure-data-lake-store-python#207]
### Description
Hello, I'm trying to copy a file from one datalake to other. I sucesfully copy a file using ADLDownloader and ADLUploader (temporary file on shm) 
In this case I would like to preserve ACL from source datalake. I run xxx.get_acl_status(file) and get an acl dict:
{'stickyBit': False, 'entries': ['user::rwx', 'group::rwx', 'group:0xxxxxx78a4751:--x', 'group:3e6xxxx94df8f9f50:r-x', 'group:bd3xxx97ecc3:rwx', 'mask::rwx', 'other::---'], 'group': 'f6bxxxxx9d2', 'permission': '770', 'owner': 'f6bb982bxxxxb985fd9d2'}

In HISTORY.rst I found this note:
   * set_acl_entries: allows for "patching" an existing ACL on a file or folder
But I get:
    AttributeError: 'AzureDLFileSystem' object has no attribute 'set_acl_entries'

### Reproduction Steps
** Enumerate the steps to reproduce the issue here:**

### Environment summary

**SDK Version:** What version of the SDK  are you using?
azure-common (1.1.8)
azure-datalake-store (0.0.18)
azure-mgmt-datalake-nspkg (2.0.0)
azure-mgmt-datalake-store (0.4.0)
azure-mgmt-nspkg (2.0.0)
azure-mgmt-resource (1.2.2)
azure-nspkg (2.0.0)

**Python Version:** What Python version are you using? Is it 64-bit or 32-bit?  
Python 3.5.2

**OS Version:** What OS and version are you using?  
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial

**Shell Type:** What shell are you using?
bash

**Comment by dgfmdrv** [comment]
Reading docs for set_acl, I could join acl['entries'] using coma an use set_acl or modify_acl_entries.

But I get an PermissionError:

> root@xxxxxxx:/home/admin/backup# time hadoop fs -ls -h adl://yyyyyy.azuredatalakestore.net/directory1
> ls: `adl://yyyyyy.azuredatalakestore.net/directory1': No such file or directory

```
token = lib.auth(tenant_id='a5xxxxxxx2b', client_id='32xxxx543', client_secret='232xxxxxx322')
adlb = core.AzureDLFileSystem(token, store_name='yyyyyy')
adlb.mkdir('directory1')
ADLUploader(adlb, 'directory1/fich_test', '/tmp/fich_test', overwrite=True)
adlb.set_acl('directory1/fich_test','user::rwx')
```
```
Traceback (most recent call last):
  File "permisos_fich.py", line 24, in <module>
    adlb.set_acl(fullpath,'user::rwx')
  File "/usr/local/lib/python3.5/dist-packages/azure/datalake/store/core.py", line 319, in set_acl
    self._acl_call('SETACL', path, acl_spec, invalidate_cache=True)
  File "/usr/local/lib/python3.5/dist-packages/azure/datalake/store/core.py", line 298, in _acl_call
    to_return = self.azure.call(action, posix_path, **parms)
  File "/usr/local/lib/python3.5/dist-packages/azure/datalake/store/lib.py", line 386, in call
    self.log_response_and_raise(r, PermissionError(path), level=exception_log_level)
  File "/usr/local/lib/python3.5/dist-packages/azure/datalake/store/lib.py", line 317, in log_response_and_raise
    raise exception
PermissionError: directory1/fich_test
```
ADLUploader function work, I can see the new directory and file but set_acl launch an exception.
get_acl_status also work.
```
root@xxxxx:/home/admin/backup# time hadoop fs -ls -h adl://yyyyyy.azuredatalakestore.net/directory1
Found 1 items
-rwxrwx---   1 bdd5cxx07a8abe 9f65xx04803a1         11 2018-03-08 10:19 adl://yyyyyy.azuredatalakestore.net/directory1/fich_test
```

If I launch a haddop command with same credentials, permissions from original file on nnnn datalake are copied to yyyyyy datalake (parameter -pa), but using set_acl I get these exception:
`hadoop fs -cp -pa adl://nnnn.azuredatalakestore.net/directory1/fich_test  adl://yyyyyy.azuredatalakestore.net/directory1/fich_test  `

Can anybody help me? Thank you

**Comment by milanchandna** [comment]
try this:
adlb.mkdir('directory1')
ADLUploader(adlb, 'directory1/fich_test', '/tmp/fich_test', overwrite=True)
adlb.modify_acl_entries('directory1','user::rwx')
adlb.modify_acl_entries('directory1/fich_test','user::rwx')

First of all set_acl overrides the previous ones whereas modify_acl_entries will only modify.
Secondly, set_acl and modify_acl_entries are not recursive. so use it on both the directory and then the file.
Let us know if this worked.

**Comment by dgfmdrv** [comment]
Hi @milanchandna 
I called set_acl method but passing only 'user::rwx' as parameter. Because of this I get PermissionError.
Your example works perfectly and I understand diferences between set_acl and modify_acl_entries 
Thank you for point me to the right way

**Comment by milanchandna** [comment]
no problem, happy to help 👍 .
