### ISSUE TITLE
python error importing data lake store: azure.mgmt.datalake.store  (Windows 8-64 bit, Python 3.6.3, Pip 9.0.2)

### ISSUE THREAD

**Issue by starhh** [Azure/azure-data-lake-store-python#210]
### Description
 (Windows 8-64 bit, Python 3.6.3, Pip 9.0.2)
Following Documentation to use azure data lake store using python (https://docs.microsoft.com/en-us/azure/data-lake-analytics/data-lake-analytics-manage-use-python-sdk), I was able to successfully install other libraries and the one below for ADLS:
pip install azure-datalake-store                                                                               #successfully install 
pip install azure-mgmt-datalake-store                                                                    #successfully install 

BUT, when i import the library following as mentioned in the documentation, I encounter the Error
(
## Required for Azure Data Lake Store account management
from azure.mgmt.datalake.store import DataLakeStoreAccountManagementClient     #Error Importing 
from azure.mgmt.datalake.store.models import DataLakeStoreAccount                       #Error Importing

## Required for Azure Data Lake Store filesystem management
from azure.datalake.store import core, lib, multithread                                                 #Error Importing
)

---

### Reproduction Steps
** Enumerate the steps to reproduce the issue here:**

Error Details:
C:\Windows\system32>python
Python 3.6.3 (v3.6.3:2c5fed8, Oct  3 2017, 17:26:49) [MSC v.1900 32 bit (Intel)]
 on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>
>>> from azure.mgmt.datalake.store import DataLakeStoreAccountManagementClient
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'azure.mgmt.datalake.store'
>>> from azure.mgmt.datalake.store.models import DataLakeStoreAccount
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'azure.mgmt.datalake.store'
>>> from azure.datalake.store import core, lib, multithread
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'azure.datalake'
>>>

### Environment summary

**SDK Version:** What version of the SDK  are you using? (pip show azure-datalake-store)
Answer here:
C:\Windows\system32>pip show azure-datalake-store
Name: azure-datalake-store
Version: 0.0.19
Summary: Azure Data Lake Store Filesystem Client Library for Python
Home-page: https://github.com/Azure/azure-data-lake-store-python
Author: Microsoft Corporation
Author-email: ptvshelp@microsoft.com
License: MIT License
Location: c:\program files\python36\lib\site-packages
Requires: cffi, msrest, adal

**Python Version:** What Python version are you using? Is it 64-bit or 32-bit?  
Answer here: 32 bit

**OS Version:** What OS and version are you using?  
Answer here: Windows 8, 64 bit

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: cmd.exe

**Comment by milanchandna** [comment]
Looks like either you have multiple version of Python installed or you are running pip and pyhton scripts from different users. To make sure follow these steps:
1. make sure same user is used for running pip and python commands.
2. run command "which -a python"
    This will show a list of python interpreters installed. When you run "python", first one will be run by default.
3. run command "which -a pip"
    This will show a list of pip installed. When you run "pip", first one will be run.
If path for first python and first pip is different, then this is the culprit.
    Use command "python -m pip install azure-datalake-store" instead of "pip install azure-datalake-store" to rectify this.
A good explanation about this: https://stackoverflow.com/a/32680082/877259 

Let me know if this worked.

**Comment by milanchandna** [comment]
Closing this as issue is not in repo but in user configuration.
