### ISSUE TITLE
On thread safety, asynchronous and deadlocks

### ISSUE THREAD

**Issue by npezolano** [Azure/azure-data-lake-store-python#213]
I'm experiencing deadlocks on a process that runs several multithreaded reads and writes.

Is this library thread safe? 

Is the call below handled asynchronously ?
```

with adl.open('anewfile', 'wb') as f:
    f.write(b'important data')

```

**Comment by milanchandna** [comment]
@npezolano ADLS is single writer semantics like HDFS. So you can still do multithreaded reads but not writes.
