### ISSUE TITLE
Use proxy with azure.datalake.store.lib.auth()

### ISSUE THREAD

**Issue by kasuteru** [Azure/azure-data-lake-store-python#217]
I am trying to use this library behind a corporate proxy and there does not seem to be a (documented) way to configure the proxy to be used with azure.datalake.store.lib.auth()? 

Here is an example how it works with the requests library:

```
import requests

proxies = {
    'http': 'http://user:pass@10.10.1.0:3128',
    'https': 'http://user:pass@10.10.1.0:3128',
}

# Create the session and set the proxies.
s = requests.Session()
s.proxies = proxies
```

**Comment by lmazuel** [comment]
Hi @kasuteru 
The most simple way will be to set the env variables, as described in the requests doc:
http://docs.python-requests.org/en/master/user/advanced/#proxies

**Comment by milanchandna** [comment]
Closing this since there is a reliable and easy way to setup the proxies.

**Comment by erlisb** [comment]
Hi @lmazuel ,

I am trying to use azure.datalake.store.lib.auth() to authenticate to AzureDLFileSystem and do some file operations there. I am behind corporate firewall so I need to use some proxy in the auth() method, but for some reasons, I am not able to..
HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /XXXXXXXXXXXXXXXXXXXXXX/oauth2/token

Is there any way to make this work, without setting proxy env variables ?

I don't have much experience with Azure python SDKs, so any kind of help would be appreciated..

Thank you,
Erlis
