### ISSUE TITLE
Add "selective overwrite based on newest date modified" option for downloads and uploads

### ISSUE THREAD

**Issue by masangster** [Azure/azure-data-lake-store-python#229]
This option would be useful in the case that, for example, I download some subdirectory of files, use some of them as inputs to calculations, and then re-upload the entire subdirectory with additional calculation outputs scattered within subfolders in the subdirectory. In the meantime however, someone has updated a new version of a file that I am using as an input. When I re-upload the subdirectory including outputs to the data lake, then my older, not updated version of the input file will overwrite the newer version uploaded by a colleague in the meantime. In this case, it would be good to have a selective overwrite based on only overwriting if the files are newer.

**Comment by akharit** [comment]
This would not be a fix just in the SDK, it would have to be an API feature that is supported in the backend. Currently that is not planned. 

However, you can do this yourself in your code by querying the last modified time or the length of the file.

I am leaving the issue open till I get some confirmation from the API side

**Comment by akharit** [comment]
Closing as this is not on the road map for now.
