### ISSUE TITLE
Maintain file structure when using ADLUploader even if directory is empty

### ISSUE THREAD

**Issue by masangster** [Azure/azure-data-lake-store-python#230]
### Description
Similar to the previous issue with the downloader, the uploader does not replicate the file structure on the remote path if the directory tree does not contain any file but only folders. This is needed to give predictable behaviour regarding whether a folder should already exist or not.

### Environment summary

**SDK Version:** What version of the SDK  are you using? (pip show azure-datalake-store)
Answer here: 0.0.27

**Python Version:** What Python version are you using? Is it 64-bit or 32-bit?  
Answer here: 3.6 64 bit

**OS Version:** What OS and version are you using?  
Answer here: Windows 7 and 10

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: VS code

**Comment by akharit** [comment]
Fixed.
