### ISSUE TITLE
AzureDLFile does not implement readinto() function

### ISSUE THREAD

**Issue by kasuteru** [Azure/azure-data-lake-store-python#232]
Some libraries expect file-like objects to have a readinto() method, see also [here](https://docs.python.org/3/library/io.html#module-io). This is currently missing for the AzureDLFile class, making using the ADLS impossible for any libraries that try to use this method.

**Comment by akharit** [comment]
@kasuteru Is there anything apart from readinto() that needs to be implemented? I do see some other functions that are not implemented for AzureDLFile class, that are mentioned for python iobase. Can you provide some example code or library that you can't use right now?

**Comment by akharit** [comment]
Fixed from release 0.0.34 onward.
