### ISSUE TITLE
Support for PyArrow

### ISSUE THREAD

**Issue by dcieslak19973** [Azure/azure-data-lake-store-python#238]
### Description
**Outline the issue here:**
PyArrow supports HDFS and S3. Would be nice if ADL (and ADL Gen 2) were supported as well.
---

### Reproduction Steps
** Enumerate the steps to reproduce the issue here:**

The ADLFS class cannot be passed in to the PyArrow Parquest DataSet class.

### Environment summary

**SDK Version:** What version of the SDK  are you using? (pip show azure-datalake-store)
Answer here: 0.30

**Python Version:** What Python version are you using? Is it 64-bit or 32-bit?  
Answer here: both

**OS Version:** What OS and version are you using?  
Answer here: Linux

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: Bash

**Comment by akharit** [comment]
@dcieslak19973 Can you please provide some stub code to reproduce the issue?

**Comment by akharit** [comment]
Needs 3rd party changes
