### ISSUE TITLE
AzureDLFileSystem does not follow PythonFilesystem Interface

### ISSUE THREAD

**Issue by yshahin** [Azure/azure-data-lake-store-python#242]
### Description
**Outline the issue here:**
Working with [Bonobo](http://docs.bonobo-project.org) lib I am unable to utilize the library cause it doesn't conform the PythonFilesystem Interface.
Current problem facing is "open() got an unexpected keyword argument 'encoding'"
---

### Reproduction Steps
** Enumerate the steps to reproduce the issue here:**
Use AzureDLFileSystem instance as a bonobo file system service

### Environment summary

**SDK Version:** What version of the SDK  are you using? (pip show azure-datalake-store)
Answer here: 0.0.31

**Python Version:** What Python version are you using? Is it 64-bit or 32-bit?  
Answer here: 64-bit v3.6.5

**OS Version:** What OS and version are you using?  
Answer here: Windows

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: Git Bash

**Comment by akharit** [comment]
@yshahin Thanks for pointing the issue! 

Can you please provide some stub code that reproduces the error?

**Comment by akharit** [comment]
This might be related to #238 and #232.

**Comment by yshahin** [comment]
Yes they are related

**Comment by akharit** [comment]
Closing as it requires text mode support i.e encoding, while adls only provides binary support.
