### ISSUE TITLE
azure/__init__.py causing issues with importing other azure components 

### ISSUE THREAD

**Issue by ankitkumarr** [Azure/azure-data-lake-store-python#266]
### Description

Installing `azure-data-lake-store` includes `azure/__init__.py`  with these line
```
__import__('pkg_resources').declare_namespace(__name__)
```
`declare_namespace` does not seem compatible with PEP420 style implicit namespace. 
So, if I have

PathA/
     ---azure/
     ------\_\_init\_\_.py (with declare_namespace)
     ------datalake/
     -----------....

PathB/
     ---azure/
     ------<some_azure_module>/
     -----------....

where both PathA and PathB are in my `PYTHONPATH`, importing `datalake` and `<some_azure_module>` will not work. 

Although Python 3.3+ (PEP 420) does not require having `__init__.py`, it might be more compatible to use-
```
from pkgutil import extend_path
__path__ = extend_path(__path__, __name__)
```
Because `extend_path` is PEP 420 and future compatible making the above scenario work. 

__Note:__
This could also be solved by holding a dependency on `azure-nspkg>=3.0.1` and not installing `__init__.py` directly, because that takes care of all scenarios.

**Comment by akharit** [comment]
There is a implicit dependency on azure-nspkg which is used during the build stage for bdist_wheel. More details are in the file azure_bdist_wheel.py . How are you installing the package so that this problem arises?

I'll change to the extend_path after checking compatibility with Python 2.7

**Comment by lmazuel** [comment]
I created a placeholder for the doc I need to write:
https://github.com/Azure/azure-sdk-for-python/wiki/Azure-packaging

**Comment by ankitkumarr** [comment]
Thank you @lmazuel and @akharit for looking into this! @akharit, this was an issue I was seeing while working on Azure functions for Python. The reason for `azure` packages in different paths were because there were some `azure` dependencies pre-installed in the server and some being brought in by the users. I think the specifics may not be very relevant here.
Thanks once again!
