### ISSUE TITLE
Save, load and run a transfer if a transfer is interrupted e.g., by user action, the transfer can be restarted at another time.

### ISSUE THREAD

**Issue by nandishjpatel** [Azure/azure-data-lake-store-python#271]
ADLUploader.save() or ADLDowloader.save() does not save a copy on a transfer process under ~/.config/azure-datalake-store
---

- A issue in azure.datalake.store.multithread.ADLUploader or ADLDownloader
https://docs.microsoft.com/en-us/python/api/azurehttps://docs.microsoft.com/en-us/python/api/azure-datalake-store/azure.datalake.store.multithread.adluploader?view=azure-python-datalake-store/azure.datalake.store.multithread.adluploader?view=azure-python

- Using save() to persist a upload/download transfer process in its current state to the disk does not generate any file under ~/.config/azure-datalake-store
https://github.com/Azure/azure-data-lake-store-python/blob/d929cf3f07f94f3162fb041384c9d29476d0689e/azure/datalake/store/multithread.py#L36-L50

- Using load() to list persisted transfer for possible resumption always returns {} an empty dictionary

- Using run() without an argument as ADLUploader or ADLDownloader gives an error: [pylint] No value for argument 'self' in unbound method call [E1120]

***Example:***
 
```
# ADLS standard python API usage to upload file(s)/directory from remote PC to ADLS
def adluploader(rpath, lpath):
    try:
        # multithread.ADLUploader.clear_saved()
        multithread.ADLUploader(adlsFileSystemClient, rpath=rpath,
                                lpath=lpath,
                                progress_callback=_update_progress).save()
    except exceptions.FileExistsError:
        print 'The directory or the file(s) in directory already exist on {} ADLS'.format(data_lake_store_name)
        overwrite_input = raw_input('Do you want to overwrite [Y/N]: ')
        if overwrite_input.upper() == 'Y':
            try:
                # multithread.ADLUploader.clear_saved()
                multithread.ADLUploader(adlsFileSystemClient, rpath=rpath,
                                        lpath=lpath,
                                        overwrite=True, progress_callback=_update_progress).save()
            except exceptions.DatalakeIncompleteTransferException:
                print 'Incomplete transfer process'
                multithread.ADLUploader.load()
                print multithread.ADLUploader.load()
                print 'Retrying'
                azure_upload = multithread.ADLUploader(adlsFileSystemClient, rpath=rpath,
                                        lpath=lpath,
                                        overwrite=True, progress_callback=_update_progress)
                multithread.ADLUploader.run(azure_upload)
        elif overwrite_input.upper() == 'N':
            print 'Exiting'
    except exceptions.PermissionError:
        print 'You do not have permission to this directory'
    except exceptions.DatalakeIncompleteTransferException:
        print 'Incomplete transfer process'
        multithread.ADLUploader.load()
        print multithread.ADLUploader.load()
        print 'Retrying'
        azure_upload = multithread.ADLUploader(adlsFileSystemClient, rpath=rpath,
                                lpath=lpath,
                                progress_callback=_update_progress)
        multithread.ADLUploader.run(azure_upload)
```

### Environment summary

**SDK Version:** What version of the SDK  are you using? (pip show azure-datalake-store)
Answer here: 0.0.39

**Python Version:** What Python version are you using? Is it 64-bit or 32-bit?  
Answer here: 2.7.12 64-bit

**OS Version:** What OS and version are you using?  
Answer here: Ubuntu 16.04 LTS

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: bash

**Comment by akharit** [comment]
Is this a regression in a recent version? As far as I can figure out, on the code sample, the exception is raised in the method while it is running so save() is never actually called. So there is no file for load() method which results in it returning empty dictionary.
```
            try:
                x = multithread.ADLUploader(adlsFileSystemClient, rpath=rpath,
                                        lpath=lpath,
                                        overwrite=True, progress_callback=_update_progress)
            except exceptions.DatalakeIncompleteTransferException:
                x.save()
                print 'Saved incomplete transfer process'
                
 ```
should save the transfer process. 

I am not sure I understood the following 
* Using run() without an argument as ADLUploader or ADLDownloader gives an error: [pylint] No value for argument 'self' in unbound method call [E1120]
Can you elaborate?

**Comment by akharit** [comment]
Closing.
