### ISSUE TITLE
ADLS Gen2 support

### ISSUE THREAD

**Issue by holger-tr** [Azure/azure-data-lake-store-python#285]
We are using this library to interact with ADLS Gen1. We would like to upgrade to ADLS Gen2. Will this library support this?

**Comment by sachinsbigdata** [comment]
ADLS Gen1 cannot and will not be used to access ADLS Gen2 enabled Storage accounts. 

For the latest on SDKs that can be used for ADLS Gen2 access please refer to this link - https://docs.microsoft.com/en-us/azure/storage/blobs/data-lake-storage-known-issues .

**Comment by akharit** [comment]
Closing this as not supported.
