### ISSUE TITLE
AzureDLFileSystem does not implement cp(path1, path2) method

### ISSUE THREAD

**Issue by pragatishah** [Azure/azure-data-lake-store-python#289]
### Description
**Outline the issue here:**
The cp method for core.AzureDLFileSystem  is not implemented. The source code for the method reveals the function is empty and raises an exception. 

cp is mentioned in the documentation here: https://docs.microsoft.com/en-us/python/api/azure-datalake-store/azure.datalake.store.core.azuredlfilesystem?view=azure-python

---

### Reproduction Steps
** Enumerate the steps to reproduce the issue here:**
 Step 1: Create core.AzureDLFileSystem object. 

azure_client = core.AzureDLFileSystem(lib.auth(**azure_config),
                                store_name=account_name)
azure_client.cp(source, destination) #raises NotImplementedError exception

### Environment summary

**SDK Version:** What version of the SDK  are you using? (pip show azure-datalake-store)
Answer here:  0.0.43

**Python Version:** What Python version are you using? Is it 64-bit or 32-bit?  
Answer here: 3.6.7, 64-bit

**OS Version:** What OS and version are you using?  
Answer here:  Windows 10

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: Bash on Windows

**Comment by akharit** [comment]
There is no efficient way of implementing cp. I'll change the documentation. I am hesitant to remove it as even though it is basically an empty method, someone may have taken a dependency on cp being present.
