### ISSUE TITLE
Low information error given when passed wrong password

### ISSUE THREAD

**Issue by hpbrewton** [Azure/azure-data-lake-store-python#293]
### Description
When trying to access a datalake I got an attribute error though the problem turned about to be an incorrect password.

---

### Reproduction Steps
** Enumerate the steps to reproduce the issue here:**
```python
from azure.datalake.store import core, lib, multithread

tenant_id = # <correct tenant>
username = # <valid username>
password = # <incorrect password>

token = lib.auth(tenant_id = tenant_id, username = username, password = password)
```
### Environment summary

**SDK Version:** What version of the SDK  are you using? (pip show azure-datalake-store)
Answer here: 0.0.46

**Python Version:** What Python version are you using? Is it 64-bit or 32-bit?  
Answer here: 64

**OS Version:** What OS and version are you using?  
Answer here: Windows 10

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: Powershell

**Comment by akharit** [comment]
@hpbrewton 
Thanks for raising this. 

What response are you currently seeing? The error is based on the python adal module, so I can forward the request there.

**Comment by akharit** [comment]
BTW, I am getting the following exception
adal.adal_error.AdalError: Get Token request returned http error: 400 and server response: {"error":"invalid_grant","error_description":"AADSTS50126: Invalid username or password .........

**Comment by akharit** [comment]
Closing as no response. Please reactivate if needed.
