### ISSUE TITLE
[Question] How to get "pythonic" access / last modified timestamps ?

### ISSUE THREAD

**Issue by glenfant** [Azure/azure-data-lake-store-python#296]
### Description

I can't find how I can make pythonic values, suitable to the "time" or "datetime"  packages, with the "accessTime" and "modificationTime" keys of the object returned by the "info(...)" method of a "AzureDLFileSystem" instance.

---

### Reproduction Steps

```python
dlfs = AzureDLFileSystem(**your_connection_params)
info = dlfs.info("/some/existing/file")
print(info["accessTime"])
# -> 1538409759284
print(info["modificationTime"])
# -> 1538410080090
```
In Python, we can play with "time.time()" that give the number of seconds since epoch (float) that can be converted to anything including "datetime.datetime" objects.

### Environment summary

Python 3.6.8 On MacOS 10.13 (High Sierra) 64 bits, azure-datalake-store 0.0.46, bash

**Comment by epa095** [comment]
Those timestams are in milliseconds instead of seconds. One way to handle them is as follows:
```python
t_stamp=1538410080090
datetime.datetime.fromtimestamp(t_stamp/1000.0) 
```

**Comment by glenfant** [comment]
@epa095 Many thanks for this fast answer !
