### ISSUE TITLE
ValueError: Token cannot be auto-refreshed.

### ISSUE THREAD

**Issue by AkshayTharval** [Azure/azure-data-lake-store-python#299]
### Description
**Outline the issue here:**
I am running a script which gets data from ADL and performs some calculations on local. I am able to run the script for 2 hours before it fails with the following error:
ValueError: Token cannot be auto-refreshed.
---

### Reproduction Steps
** Enumerate the steps to reproduce the issue here:**
from azure.datalake.store import core, lib, multithread

token = lib.auth()
adlsFileSystemClient = core.AzureDLFileSystem(token, store_name='yourADL')

# Below line is where issue is observed
with adlsFileSystemClient.open(your_path_to_file) as f:
    # Do something

### Environment summary
Python: 3.6.8

**SDK Version:** What version of the SDK  are you using? (pip show azure-datalake-store)
azure.datalake.store __version__ = "0.0.44"

**Python Version:** What Python version are you using? Is it 64-bit or 32-bit?  
Answer here: 64

**OS Version:** What OS and version are you using?  
Answer here: Windows 10 Enterprise

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: Using Jupyter and anaconda ( I dont know that answers your question)

Let me know what more information you need.

**Comment by akharit** [comment]
The relevant code line is
        if self.token.get('refresh', False) is False and (not self.token.get('secret') or not self.token.get('client')):
            raise ValueError("Token cannot be auto-refreshed.")

You can check what fields your token has by

       cred = lib.auth()
       for (k,v) in cred.token.items():
             print(k, v)

If refresh field is false, we can't refresh token. 

This is token specific and is controlled by Azure Active Directory. You'll have to check with the account admin to allow tokens to be refreshed.

Similar to issue https://github.com/Azure/azure-data-lake-store-python/issues/158

**Comment by akharit** [comment]
Closing as this is probably an issue with AAD

**Comment by mounir-futurefacts** [comment]
@akharit 

I used your suggestion for checking if the token can be auto-refreshed with 
```
   cred = lib.auth()
   for (k,v) in cred.token.items():
         print(k, v)
```
I find that the refresh and refreshToken fields actually hold a refresh token. 
Considering this, could this then still be an AAD issue? 

NB: the script is constantly running and makes calls to the adlsFileSystemClient every 24 hours. (it failed last night with `token cannot be auto refreshed`. Traceback included here:
[traceback.txt](https://github.com/Azure/azure-data-lake-store-python/files/4096072/traceback.txt)

**Comment by eduardofb** [comment]
Hi @mounir-futurefacts. I'm having the same problem when running long jobs in my development environment. Did you manage to solve it?
