### ISSUE TITLE
Can files be filtered based on Last Modified time?

### ISSUE THREAD

**Issue by karthiksubramanians** [Azure/azure-data-lake-store-python#300]
### Description
**Outline the issue here:**

I am trying to perform in-memory operations on files stored in azure datalake. I am unable to find documentation regarding using a matching pattern without using the ADL Downloader.

For a single file, this is the code I use
```

filename = '/<folder/<filename>.json'
with adlsFileSystemClient.open(filename) as f:
    for line in f:
         <file-operations>
```

But how do we filter based on filename (string matching) or based on last modified date.

When I used U-SQL , I had the option to filter the fileset based on the last modified option. 

```
DECLARE EXTERNAL @TodaysTime = DateTime.UtcNow.AddDays(-1);

@rawInput=
    EXTRACT jsonString string,
            uri = FILE.URI()
            ,modified_date = FILE.MODIFIED()
    FROM @in
    USING Extractors.Tsv(quoting : true);



@parsedInput=
    SELECT *
    FROM @rawInput
    WHERE modified_date > @TodaysTime;
```

Is there any similar options to filter the files modified during a specified period when using adlsFileSystemClient?

Any help is appreciated.

---

### Environment summary

**SDK Version:** What version of the SDK  are you using? (pip show azure-datalake-store)
Answer here: 0.0.47

**Python Version:** What Python version are you using? Is it 64-bit or 32-bit?  
Answer here: 3.6.5 - 64bit

**OS Version:** What OS and version are you using?  
Answer here: Windows 10

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: Jupyter Notebook (Anaconda Navigator)

**Comment by karthiksubramanians** [comment]
Any updates on this?

**Comment by akharit** [comment]
We do return last modified time for ls command with detail=True. 

Does that work for you?

**Comment by karthiksubramanians** [comment]
Could it be used to filter for files modified in a specific period. I can see the file modified time is ls but can it be used in a query like "files from last 4 hours" (like in the U-SQL functionality) ?

**Comment by akharit** [comment]
There isn't any in build functionality in the adls sdk itself as there is no server side api that will return only files modified with the last 4 hours.
It should be easy to write the code to do that after you get the list of all entries. 

The modification time field returns milliseconds since unix epoch, which you can convert to a python datetime object by
        
          from datetime import datetime, timedelta
         datetime.fromtimestamp(file['modificationTime'] / 1000)

And then something like 
     
    filtered = [file['name'] for file in adl.ls('/', detail=True) if (datetime.now() - datetime.fromtimestamp(file['modificationTime']/1000)) > timedelta(hours = 4)]

You can use walk instead of ls for recursive enumeration as well.

**Comment by karthiksubramanians** [comment]
This works well for the requirement! Thanks for the response!
