### ISSUE TITLE
Readme.md contains an unresolved merge conflict

### ISSUE THREAD

**Issue by jamesclarke** [Azure/azure-data-lake-store-python#305]
[Readme.md](https://github.com/Azure/azure-data-lake-store-python/blob/ef82296ba2c00b3d702d4ed33309d3813eec2516/Readme.md#api) contains an unresolved merge conflict introduced in ef82296ba2c00b3d702d4ed33309d3813eec2516.

**Comment by gregroberts** [comment]
+1

If the author can't git properly, why should we rely on them for anything else?

**Comment by akharit** [comment]
Sorry. Missed the first email on this.
