### ISSUE TITLE
What is the relationship between this library and azure-storage-file-datalake

### ISSUE THREAD

**Issue by markusweimer** [Azure/azure-data-lake-store-python#311]
I am looking for the right API to use to connect to Azure Data Lake Storage. Upon my search, I came across this library and the `azure-storage-file-datalake` which is used by the documentation found [here](https://docs.microsoft.com/en-us/samples/azure/azure-sdk-for-python/storage-datalake-samples/). 

What is not clear to me is which one of those to use? Is one going to replace the other? Or do they solve different aspects of the access to data lake?

**Comment by akharit** [comment]
@markusweimer This library is for adls gen1 while the one you have in the link is for adls gen2

**Comment by markusweimer** [comment]
@akharit Thanks! This library seems to be more desirable because it also provides File-like objects. Do you know whether that is coming to `azure-storage-file-datalake`?

**Comment by akharit** [comment]
@markusweimer I don't have information on that. Perhaps you can open an issue on this repo https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/storage/azure-storage-file-datalake ?

**Comment by markusweimer** [comment]
Thanks! I filled #312 to update the `README.md` to help with the confusion about Gen1 vs. Gen2.

**Comment by akharit** [comment]
Thanks for the pr!
