### ISSUE TITLE
General view of the SDK choices

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-data-lake-store-python#33]
It will be very helpful for us to have a big picture of the choice you make for the SDK architecture. Clearly you have experience on big data services and it's amazing how the project advance. But i would like a like step back to better understand how amazing it is :)

Example:
- What is `dask` and why do you it's important to follow this framework? Why do you think the future adlfs customers, which are datalake specialist, will be be glad that lib follow dask?
- What are doing our competitors? Like Amazon, Google, etc.? Are they following dask too? If not, why do not choose to follow their pattern to facilitate  the transition to Azure Datalake?

Thanks

**Comment by begoldsm** [comment]
@lmazuel @martindurant @mcg1969 I am going to close out this issue based on the conversation that we have above. I think that, in terms of usability of the surface area we can have @matt1883 work with our usability teams. In terms of maintainability and general code health, I encourage @lmazuel and @mcg1969 as well as the rest of our internal (and external!) python partners to make recommendations, open specific issues and "keep us honest" so to speak.

Finally, I will be working with @martindurant and @jbcrail during our final packaging milestone to make sure we have a clear "design doc" available in our docs that explains what we did and why we did it.

As always, if you feel that there is something that remains here, please re-open this issue, and thanks!
