### ISSUE TITLE
More flexibility with trace logging

### ISSUE THREAD

**Issue by begoldsm** [Azure/azure-data-lake-store-python#47]
Currently we see a lot of general debug logging when executing, especially on large files/folders. Ideally, it would be good to be able to turn this on/off and have the ability to tweak verbosity (from debug all the way to just error cases). I am not sure if this is possible, but it would also be good to be able to optionally print out the request/response in a nice format. For example, PowerShell today hooks into the tracing logging that takes place within the standard .NET sdk to enable things like this if the user wants to debug what is actually being sent:

Get-AzureRmDataLakeAnalyticsAccount -Debug
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://api-dogfood.resources.windows-int.net/subscriptions/90585f39-ab85-4921-bb37-0468f7efd1dd/providers/Microsoft.Da
taLakeAnalytics/accounts?api-version=2015-10-01-preview

Headers:
x-ms-client-request-id        : fe5fda9a-fd40-475f-9dec-a35c2ae7fe0c
accept-language               : en-US

Body:

DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Pragma                        : no-cache
x-ms-original-request-ids     :
ed2622ab-58bf-4cef-b960-650f971e6ada,eea2a95c-20e1-49c9-ba4a-310e31b3ffd4,dc27ecf2-8a38-4d01-94f7-ddd8f9bdc171
x-ms-ratelimit-remaining-subscription-reads: 14863
x-ms-request-id               : c55140b3-5d56-409e-a5c3-2d668b8b1134
x-ms-correlation-request-id   : c55140b3-5d56-409e-a5c3-2d668b8b1134
x-ms-routing-request-id       : CENTRALUS:20160901T233000Z:c55140b3-5d56-409e-a5c3-2d668b8b1134
Strict-Transport-Security     : max-age=31536000; includeSubDomains
Cache-Control                 : no-cache
Date                          : Thu, 01 Sep 2016 23:29:59 GMT

Body:
{
  "value": [
    {
      "properties": {
        "provisioningState": "Succeeded",
        "state": "Active",
        "endpoint": "e2etestkonappebn3p.konaaccountdogfood.net",
        "accountId": "61ab843c-2f11-42cc-9f1d-851b69d1281f",
        "creationTime": "2016-08-11T22:58:35.9195777Z",
        "lastModifiedTime": "2016-08-11T22:58:35.9195777Z"
      },
      "location": "brazilsouth",
      "tags": null,
      "id":
"/subscriptions/90585f39-ab85-4921-bb37-0468f7efd1dd/resourceGroups/konagroup-ppe-bn3p/providers/Microsoft.DataLakeAnal
ytics/accounts/e2etestkonappebn3p",
      "name": "e2etestkonappebn3p",
      "type": "Microsoft.DataLakeAnalytics/accounts"
    } ...
}

**Comment by rrenfrow86** [comment]
Update: logging is now controlled by the default python logger; we don’t have a lot of verbosity options (DEBUG produces a lot, INFO almost nothing).

**Comment by begoldsm** [comment]
@rrenfrow86 as long as debug logging gives us:
1. the request id of the request
2. the request id of the response
3. the payload of the response in the event of failure.

Then that should be ok.

**Comment by rrenfrow86** [comment]
@jbcrail - can you answer if the above comment is true?

**Comment by jbcrail** [comment]
@rrenfrow86 We don't log that info at this time.

**Comment by begoldsm** [comment]
@jbcrail do we include the following in the header for all the requests we send?
x-ms-client-request-id: <some GUID, like: 4da72a13-729f-47b3-8dfd-65768d9040ea>

**Comment by jbcrail** [comment]
@begoldsm No, is this required for every REST call?

**Comment by begoldsm** [comment]
@jbcrail yes, in order to be consistent with the rest of Azure. This also enables us to properly debug issues with specific calls into the service.

**Comment by jbcrail** [comment]
@begoldsm Do other SDKs generate a random GUID/UUID for each request call?

**Comment by begoldsm** [comment]
@jbcrail yes, here is what it looks like in the generated Azure clients:
```
url = self._client.format_url(url, **path_format_arguments)

        # Construct parameters
        query_parameters = {}
        query_parameters['api-version'] = self._serialize.query("self.config.api_version", self.config.api_version, 'str')

        # Construct headers
        header_parameters = {}
        header_parameters['Content-Type'] = 'application/json; charset=utf-8'
        if self.config.generate_client_request_id:
            **header_parameters['x-ms-client-request-id'] = str(uuid.uuid1())**
        if custom_headers:
            header_parameters.update(custom_headers)
        if self.config.accept_language is not None:
            header_parameters['accept-language'] = self._serialize.header("self.config.accept_language", self.config.accept_language, 'str')

        # Construct and send request
        request = self._client.get(url, query_parameters)
        response = self._client.send(request, **header_parameters**, **operation_config)
```

**Comment by begoldsm** [comment]
@jbcrail I couldn't bold inside of the code block, but you can see the '**' wrapped sections where the x-ms-client-request-id is set and then passed in to the request.

**Comment by begoldsm** [comment]
This is now done and we are getting much more information in both debug logs and error logs.
