### ISSUE TITLE
Uploader fails if the full path to the target file doesn't exist

### ISSUE THREAD

**Issue by begoldsm** [Azure/azure-data-lake-store-python#48]
Creation of a file in ADLS does not require the underlying path to exist. The create call itself will create the entire path or throw if it can't. The recommendation is to remove this requirement and fail only if the target file itself can't be created (which should still be tested for at the very beginning).

**Comment by rrenfrow86** [comment]
Believe this is no longer an issue - @begoldsm please confirm.

**Comment by begoldsm** [comment]
Verified, thank you!
