### ISSUE TITLE
Improvement Recomendation: More unique "tmp" folder per file/folder upload

### ISSUE THREAD

**Issue by begoldsm** [Azure/azure-data-lake-store-python#49]
This is a minor optimization which helps with the finalization step for each file. There is an option within the concatenate call: op=MSCONCAT&deleteSourceDirectory=true.

This call, instead of deleting each file individually, deletes the entire folder instead. This can be used if the only contents in the folder are just the contents for the file being concatenated and it drastically increases the performance of the concatenate operation. 
Additionally, MSCONCAT should be the operation used (not op=CONCAT) due to the fact that, for very large files (or paths) putting all of those in the URI can result in failure. MSCONCAT puts all of that content in the body instead, which has a much larger capacity.

**Comment by begoldsm** [comment]
The specific syntax for an msconcat body is a little strange, though, so be warned :).
Content-Type:application\octet-stream

request body must be a stream that, prior to becoming a byte stream, looked like this:
sources=/this/is/path/1.txt,/this/is/path/2.txt,.../this/is/path/n.txt

**Comment by begoldsm** [comment]
This is in progress in PR #81

**Comment by rrenfrow86** [comment]
@begoldsm - this is a duplicate of #73 - recommend closing this issue.

**Comment by begoldsm** [comment]
Agreed. closing this out as a duplicate.
