### ISSUE TITLE
Task 1.1: 1:1 mapping of filesystem REST endpoints

### ISSUE THREAD

**Issue by rrenfrow86** [Azure/azure-data-lake-store-python#5]
1:1 mapping of filesystem REST endpoints to client methods

**Comment by begoldsm** [comment]
@martindurant Sorry for the delay here. setpermissions and setowner are now supported in our production cluster so they are testable. I am closing this work item, though since everything is implemented and I will open a new issue for the current milestone to add some tests for these APIs.
