### ISSUE TITLE
ADLUploader defaults to overwrite if file exists

### ISSUE THREAD

**Issue by begoldsm** [Azure/azure-data-lake-store-python#53]
The operation should fail and the user should be told that they must explicitly use a force flag to overwrite an existing file when using ADLUploader. Today I can re-run the same upload command to the same target location and it won't complain.

**Comment by jbcrail** [comment]
1. In the case that the remote path is a directory, should we enumerate through the contained files, test for existence, and throw an error as appropriate? Or should we check if the remote directory exists and throw an error as appropriate?

1. Should ADLDownloader have a similar overwrite check?

**Comment by begoldsm** [comment]
@jbcrail for now lets do the simplest case. If the folder to upload to exists and is not empty, simply fail indicating that the caller should pass in `force` or `overwrite` or whatever we want to call it. This should hold true for upload and download.

**Comment by begoldsm** [comment]
Spoke with @jbcrail about the path's being inverted when a FileExistsError is raised. @martindurant will fix it as part of his current PR. I will re-validate after that and then close out this issue.

**Comment by begoldsm** [comment]
This has been fixed and validated.
