### ISSUE TITLE
Lower Pri: Large folder upload/download has a large startup cost in time

### ISSUE THREAD

**Issue by begoldsm** [Azure/azure-data-lake-store-python#54]
When uploading or downloading a very large directory, we see a large startup cost where the client is getting all the information it needs to begin (or resume) the operation. This could benefit from some parallelization or optimizations to reduce the amount of time needed to setup the operation.

The current timing is about 30 seconds for a folder with 10,000 1mb files in a nested structure.

**Comment by martindurant** [comment]
It turns out that `os.scandir` (and it's backport package scandir for py2) is much more efficient at getting lists of files and file sizes/attributes than walk and stat, especially on windows. https://github.com/benhoyt/scandir

**Comment by begoldsm** [comment]
@martindurant I believe you fixed this, right? Can you point to the PR that resolved this issue?

**Comment by martindurant** [comment]
No, this was not yet addressed. As above, I have a potential solution, but scandir for python2 requires compilation, so we cannot require it (it can be got via conda, of course). At the risk of complicating the logic, we could use scandir *if* present.

**Comment by begoldsm** [comment]
@martindurant I would caution against complicating the logic at this point, and the time spent up front is not high enough to warrant this (as indicated with the lower priority for this issue). We can keep this open for the future and consider that improvement down the road, if necessary.

**Comment by begoldsm** [comment]
I am closing this and marking it as an enhancement to be revisited in the future, as this is not a high priority item.
