### ISSUE TITLE
SetOwner and SetPermission are now supported, need tests

### ISSUE THREAD

**Issue by begoldsm** [Azure/azure-data-lake-store-python#59]
Please add tests and recordings for these two APIs now that they are supported

**Comment by begoldsm** [comment]
@jbcrail can you make sure we get tests and recordings for these two APIs?

**Comment by jbcrail** [comment]
@begoldsm It looks like we have coverage and recordings for SetPermission (`adlfs.chmod`), but we are missing tests for SetOwner (`adlfs.chown`). I'll work on SetOwner.

**Comment by begoldsm** [comment]
Closing this issue as the SetOwner tests are now checked in. thanks @jbcrail!
