### ISSUE TITLE
PRI 0: Use the Offset parameter in append to ensure we are always appending at the offset we expect

### ISSUE THREAD

**Issue by begoldsm** [Azure/azure-data-lake-store-python#66]
The append API allows for a query parameter called offset, which allows you to specify where you think the end of the file is to append data to. This is very useful for us, since it allows us to submit an append call where we "think" the file should currently be. If data has already been uploaded at that location, you will receive a 400 error with a BadOffsetException, which you can catch. This will indicate that data is already at that location and we can move on to the next 4mb chunk to upload. This will help preserve the uploaded file and ensure that its final length is the same as the source file.

Here is a sample request/response where the offset is not the end of the file (meaning there is already data at or ahead of the offset specified):

**Request:** 
POST https://adlspysample01.azuredatalakestore.net/webhdfs/v1/sample.txt?op=APPEND&append=true&**offset=4**&api-version=2015-10-01-preview HTTP/1.1
x-ms-client-request-id: 33401497-4ac0-451e-ab13-eccd305e3706
accept-language: en-US
Authorization:
User-Agent: Microsoft.Azure.Management.DataLake.Store.DataLakeStoreFileSystemManagementClient/0.12.6-preview AzurePowershell/v2.1.0.0
CommandName: Add-AzureRmDataLakeStoreItemContent
ParameterSetName: __AllParameterSets
Content-Type: application/octet-stream
Host: adlspysample01.azuredatalakestore.net
Content-Length: 4
Expect: 100-continue

test

**Response**
HTTP/1.1 400 Bad Request
Cache-Control: no-cache
Pragma: no-cache
Content-Length: 260
Content-Type: application/json; charset=utf-8
Expires: -1
x-ms-request-id: a8b65992-21f3-4c5d-8fe0-f0b49d0320f1
Server-Perf: [a8b65992-21f3-4c5d-8fe0-f0b49d0320f1][ AuthTime::0::PostAuthTime::0 ][S-FsOpenStream :: 00:00:010 ms]%0a[BufferingTime :: 00:00:000 ms]%0a[WriteTime :: 00:00:000 ms]%0a[S-FsAppendStream :: 00:00:036 ms]%0a[S-FsCloseHandle :: 00:00:001 ms]%0a[APPEND :: 00:00:269 ms]%0a
x-ms-webhdfs-version: 16.07.18.01
Status: 0x83090015
X-Content-Type-Options: nosniff
Strict-Transport-Security: max-age=15724800; includeSubDomains
Date: Thu, 15 Sep 2016 01:21:15 GMT

**{"RemoteException":{"exception":"BadOffsetException","message":"FsAppendStream failed with error 0x83090015 (Bad offset). [a8b65992-21f3-4c5d-8fe0-f0b49d0320f1][2016-09-14T18:21:16.0457431-07:00]","javaClassName":"org.apache.hadoop.fs.adl.BadOffsetException"}}**

**Comment by martindurant** [comment]
Would you mind providing more information on where to sue this? Currently we only ever append to the end of a file. Are you thinking of restarting uploads of files that were only partially uploaded last time, to skip sections? Now we would create the file from scratch - but this is no slower than checking each 4MB chunk for the error above.

**Comment by begoldsm** [comment]
@martindurant This is a robustness and resiliency scenario. You can only ever append at the end of a file, however if we have retry logic in our append requests, we could end up appending duplicate data, since the server doesn't care if you append the same data to the end of the file twice. By explicitly telling the server where you think the end of the file is, you can prevent this. The server will look at the offset you supplied and, if it is the end of the file as you expect, then everything works as normal. If it is not (meaning that a previous append succeeded on the server, even though the front end may have reported a failure), then you can mark the current chunk as completed and move on.

The goal isn't to change the resume/restart functionality, but to do our best in the client to ensure that, when we finish the upload, we are reasonably confident that we only uploaded the exact data we were given, resulting in a file that is identical to the one supplied.

**Comment by begoldsm** [comment]
@jbcrail I think this is partially resolved. We do now append at the specific offset, but I don't believe there is logic to catch an append that has already succeeded on the server but was retried (either due to a false failure or a transient network drop for the response). The result of the retry will be a `BadOffsetException` that looks like the below with a 400 response:

```{"RemoteException":{"exception":"BadOffsetException","message":"FsAppendStream failed with error 0x83090015 (Bad offset). [3f56efc4-7ab9-4908-9a12-028a0ca74e9f][2016-09-28T16:02:46.3881083-07:00]","javaClassName":"org.apache.hadoop.fs.adl.BadOffsetException"}}```

We should do an `Except` here if we get this error on a retry of an append and, if this is the error, mark the chunk that we were trying to append as succeeded and move on, instead of ultimately failing, which I believe is what will happen today, right?

**Comment by begoldsm** [comment]
@jbcrail @martindurant this is partially fixed. I am not sure if we will be able to make the full fix within the multithread.py/transfer.py logic right now, but that is where the catching should happen for the appends if the data has already been uploaded. We should not make changes to the core.py implementation of the APPEND call to just return if a BadOffsetException is returned, since there will be other callers of this API (other than our transfer clients) and that could be some unexepected behavior for them. I will keep this open to track as well as Martin's PR. to maintain the comment history.

**Comment by TVMKISHORE** [comment]
Hello All ,
I am getting the below while writing file to storage location . Is it the same you guys are discussing here.

org.apache.spark.SparkException: Task failed while writing rows
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.org$apache$spark$sql$execution$datasources$FileFormatWriter$$executeTask(FileFormatWriter.scala:270)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$$anonfun$write$1$$anonfun$apply$mcV$sp$1.apply(FileFormatWriter.scala:189)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$$anonfun$write$1$$anonfun$apply$mcV$sp$1.apply(FileFormatWriter.scala:188)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:108)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:338)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: APPEND failed with error 0x83090015 (Bad request. Invalid offset.). [5c120a85-5670-4e90-bdb9-30a01715eb6e][2018-12-06T11:17:45.9755155-08:00] [ServerRequestId:5c120a85-5670-4e90-bdb9-30a01715eb6e]
	at com.microsoft.azure.datalake.store.ADLStoreClient.getRemoteException(ADLStoreClient.java:1191)
	at com.microsoft.azure.datalake.store.ADLStoreClient.getExceptionFromResponse(ADLStoreClient.java:1154)

**Comment by akharit** [comment]
@TVMKISHORE This issue seems to be related to the java sdk, rather than python sdk. This issue page is for the python sdk. 
Can you open an issue there(https://github.com/Azure/azure-data-lake-store-java)? 

Also, please add the account name and time of the error(preferably as recent as possible), and the sdk version so we can investigate this error.
