### ISSUE TITLE
Can no longer pass the store name or url_suffix into AzureDLFileSystem. Only option is env variable

### ISSUE THREAD

**Issue by begoldsm** [Azure/azure-data-lake-store-python#72]
In the comments it indicates there is a param called "store". In reality, this is the constructor definition for AzureDLFileSystem (including the comments of what the args are claimed to be as well):

**store : str ("")**
        Store name to connect to
    token : dict
        When setting up a new connection, this contains the authorization
        credentials (see `lib.auth()`).
    **url_suffix: str (None)**
        Domain to send REST requests to. The end-point URL is constructed
        using this and the store_name. If None, use default.
    kwargs: optional key/values
        For auth, such as username, password. See ``lib.auth()``
def __init__(self, token=None, **kwargs)

Note that store and url_suffix are both  missing from the list.

**Comment by martindurant** [comment]
Ah, just a name mis-match: it should be `store_name`. Everything in `kwargs` is passed to the REST instance, of which `store_name` and `url_suffix` construct the URL base, and others are passed to `auth()`.

**Comment by begoldsm** [comment]
@martindurant gotcha, so its just a doc bug. We should probably include all of the important names in the documentation directly, and then continue to have the existing kwargs doc for key/value pairs.
