### ISSUE TITLE
Auth with user name and password does not work

### ISSUE THREAD

**Issue by avaranovich** [Azure/azure-data-lake-store-python#96]
`token = lib.auth(tenant_id, username, password)`

gives

`adal.adal_error.AdalError: Get Token request returned http error: 400 and server response: {"error":"invalid_request","error_description":"AADSTS90014: The request body must contain the following parameter: 'client_id'.\r\nTrace ID: 899e028b-469f-4dba-ab97-518e5a3e42e5\r\nCorrelation ID: 24bd2ce3-b084-40ab-9e8f-46f5a54ac501\r\nTimestamp: 2016-10-06 09:21:19Z","error_codes":[90014],"timestamp":"2016-10-06 09:21:19Z","trace_id":"899e028b-469f-4dba-ab97-518e5a3e42e5","correlation_id":"24bd2ce3-b084-40ab-9e8f-46f5a54ac501"}`

and according to this line https://github.com/Azure/azure-data-lake-store-python/blob/dev/azure/datalake/store/lib.py#L106

it cannot work just with username and password.

**Comment by begoldsm** [comment]
@jbcrail @martindurant this appears to be an issue with how we are defaulting the client ID. I am going to make a small change to properly default the client ID, which should resolve this issue.

@avaranovich to work around this please pass in the following client_id during authentication: 1950a258-227b-4e31-a9cf-717495945fc2

**Comment by begoldsm** [comment]
@avaranovich this should now be resolved with the latest build.
